apps/controllerx/controllerx.py

Hello, thanks for a great project!
I've added the deconz event mappings for the E1743Controller.

Added support for deconz in E1743Controller

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new_device.md
.github/ISSUE_TEMPLATE/question.md

Hi @xaviml ,
I added a few details to the different issue templates, in addition to what you had already committed in the past days. I also made some edits to the formatting, let me know what you think about the final result and if there are some changes you'd like to apply.
Regarding the "New device support" template, another great plus could be a doc page describing the process of obtaining action mappings for the integrations ControllerX currently supports. This would provide a guideline for people who want a new device to be added but don't know how to get action mappings. 👍 
P.S. I noticed you made a huge refactor on both the code and the documentation, that's a lot of work! The custom controller feature is just amazing.💪 
Thank you for putting so much effort on ControllerX and …

Improvements to issue templates

---

apps/controllerx/devices/smartthings.py
docs/_data/controllers/IM6001-BTP01.yml

Fix zha mappings for hold on ST Button

---

.gitignore
apps/controllerx/const.py
apps/controllerx/core/type/switch_controller.py
apps/controllerx/devices/ikea.py
docs/_data/controllers/E1743.yml
docs/index.md
docs/start/configuration.md
tests/core/type/switch_controller_test.py

Closes #65 
Hey @xaviml, is this what you had in mind?

Add a switch controller and E1743 implementation

---

apps/controllerx/cx_core/integration/z2m.py

As requested in #137 :) 
I hope this is enough to make the topic variable :) 
Can you point me where to change some documentation about this functionality?

Make the topic variable (Fixxes: #137)

---

apps/controllerx/cx_devices/livarno.py
docs/_data/controllers/HG06323.yml

Sorry, I'm not able to manage all that pre-commit stuff. I hope it works also like that.

add zha support for HG06323 (Lidl/Livarno)

---

apps/controllerx/cx_devices/ikea.py
docs/_data/controllers/E1812.yml

These are the Deconz button mappings for E1812LightController and E1812SwitchController.

Integration of E1812 Ikea Shortcut Button with Deconz

---

.gitignore
CONTRIBUTING.md
RELEASE_NOTES.md
apps/controllerx/cx_core/controller.py
azure-pipelines.yml
setup.cfg
tests/conftest.py
tests/integ_tests/integ_test.py

AppDaemon will soon drop support for Python3.6 and add support for Python3.9.

perf(python): deprecate python 3.6

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/aqara.py
docs/_data/controllers/WXCJKG13LM.yml

Added ZHA integration support for WXCJKG13LMLightController (Aqara Apple 6 button remote).

Added ZHA integration support for WXCJKG13LMLightController (Aqara Apple 6 button remote).

---

RELEASE_NOTES.md
apps/controllerx/cx_const.py
apps/controllerx/cx_core/action_type/predefined_action_type.py
apps/controllerx/cx_core/type/light_controller.py
apps/controllerx/cx_devices/rgb_genie.py
docs/advanced/predefined-actions.md
docs/others/integrations.md
tests/integ_tests/integ_test.py
tests/integ_tests/predefined_action_attrs/config.yaml
tests/integ_tests/predefined_action_attrs/set_brightness_test.yaml
tests/integ_tests/predefined_action_attrs/sync_test.yaml
tests/unit_tests/cx_core/action-types/predefined_action_type_test.py
tests/unit_tests/cx_core/custom_controller_test.py
tests/unit_tests/cx_core/type/light_controller_test.py

feat(action_type): allow parameters to predefined actions

---

RELEASE_NOTES.md
apps/controllerx/cx_core/integration/deconz.py
apps/controllerx/cx_core/integration/lutron_caseta.py
apps/controllerx/cx_core/integration/zha.py
docs/others/integrations.md
tests/test_utils.py
tests/unit_tests/cx_core/color_helper_test.py
tests/unit_tests/cx_core/controller_test.py
tests/unit_tests/cx_core/integration/deconz_test.py
tests/unit_tests/cx_core/integration/lutron_test.py
tests/unit_tests/cx_core/integration/mqtt_test.py
tests/unit_tests/cx_core/integration/state_test.py
tests/unit_tests/cx_core/integration/z2m_test.py
tests/unit_tests/cx_core/integration/zha_test.py
tests/unit_tests/cx_core/type/cover_controller_test.py
tests/unit_tests/cx_core/type/light_controller_test.py
tests/unit_tests/cx_core/type_controller_test.py

feat(integration): allow listen to unique id for deconz

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/philips.py
docs/device_template.md
docs/docs/controllers.md
docs/gen_device_pages.py
docs/main.py
docs/notes.yaml

fix(hue-dimmer): change z2m mapping to be compatible with non-legacy mapping

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/philips.py

feat(device): add Z2M support to HueSmartButton controller

---

apps/controllerx/cx_core/type/z2m_light_controller.py
docs/docs/start/integrations.md
docs/docs/start/type-configuration.md
tests/integ_tests/z2m_light_controller_with_mqtt/config.yaml

fix: move base_topic to Z2MLightEntity and rename to topic_prefix

---

.pre-commit-config.yaml
apps/controllerx/cx_core/type/z2m_light_controller.py
tests/integ_tests/z2m_light_controller/hold_onoff_test.yaml
tests/integ_tests/z2m_light_controller/hold_test.yaml
tests/integ_tests/z2m_light_controller/hold_toggle_test.yaml
tests/integ_tests/z2m_light_controller/release_with_no_hold_test.yaml
tests/integ_tests/z2m_light_controller_attr_from_controller/brightness_from_controller_angle_test.yaml
tests/integ_tests/z2m_light_controller_with_mqtt/hold_test.yaml

fix(z2m-light-controller): send only 1 release attribute mqtt topic

---

.github/workflows/cicd.yaml
RELEASE_NOTES.md
apps/controllerx/cx_devices/philips.py

feat(device): add deCONZ support for Philips929002398602

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/aqara.py

feat(device): add deCONZ support to WXCJKG11LM light controller

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/aqara.py

feat(device): add Z2M Light Controller support to WXKG07LMZ

---

RELEASE_NOTES.md
apps/controllerx/cx_core/integration/__init__.py
apps/controllerx/cx_core/integration/event.py
docs/docs/advanced/event-integration.md
docs/docs/start/integrations.md
docs/mkdocs.yml
docs/notes.yaml
tests/unit_tests/cx_core/integration/event_test.py
tests/unit_tests/cx_core/integration/integration_test.py

This integration is meant to be used for a custom event and it is not attached to any type of integration
related to #546, #561

feat(integration): add event integration

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/ikea.py

fix(device): fix default mapping for ICTCG1 with z2m

---

docs/docs/examples/tasmota-double-button.md
docs/docs/start/integrations.md
docs/mkdocs.yml

This is a new example for Tasmota, this time using the new integration.
This is an example of how to use two buttons to control one RGB light.
I'm not sure if something is missing, if it is just tell me and I'll update the PR accordingly.

Added example for Tasmota Two Button Device

---

docs/docs/start/type-configuration.md

Fix typo in docs

---

RELEASE_NOTES.md
apps/controllerx/cx_devices/lutron.py

feat(device): add Z2M support to Z31BRL
