xaviml/controllerx

apps/z2m_ikea_controller/z2m_ikea_controller.py
This PR is a bug fix for the last issue described in PR #5.
The issue was caused by some `rotate_left` / `rotate_right` events sent in conjunction with the `rotate_left_quick` message, which is used to turn the bulb off. These unwanted messages triggered a dimming action which was not stopped by the `self.off()` call, thus continuing to change brightness after the lamp was turned off, with the result of the lamp being turned on again or, in some cases, the lamp not being turned off and having its brightness dimmed down.
Calling the `self.release()` method before turning the light off or full on ensures that any dimming action currently running stops and doesn't affect the bulb brightness anymore.
Succesfully tested with `delay : 50` in the app configuration.
=> ICTC-G-1 bug fix

apps/z2m_ikea_controller/z2m_ikea_controller.py
In IKEA Zigbee implementation controllers have the ability to turn on the connected bulb (or light group) at minimum brightness if the action to increment brightness occurs (i.e. pressing the dedicated button for a `E1810`, turning the device to the right for a `ICTC-G-1` etc.).
This PR implements the feature, which can be device restricted, since not all controllers which will be integrated in the future could be designed to have this capability.
The `supports_from_off_to_min_brightness()` method, which can be overridden by every controller, defines whether the device supports this feature or not. By default, devices will not implement this feature.
Also, I had to edit `before_action()` signatures, passing action arguments to the methods, something that could come in handy if more …
=> Add device-restricted off to min brightness feature

apps/z2m_ikea_controller/z2m_ikea_controller.py
The Ikea `E1810`, with its 5 buttons and all the different events it can fire, is a feature-rich and flexible device. Given its versatility due to its design, it is not only suitable for controlling light brightness and temperature, but works perfectly also as a media player controller.
This PR enables support for the `E1810` as a media player controller (both for `zigbee2mqtt` and `deCONZ`). Actions are mapped as it follows :
* `brightness_up_hold`:  volume up (hold, multiple steps)
* `brightness_up_release`: volume up (release)
* `brightness_up_click`: volume up (single step)
* `brightness_down_hold`: volume down (hold, multiple steps)
* `brightness_down_release`: volume down (release)
* `brightness_down_click`: volume down (single step)
* `toggle`: play/pause
* `arrow_right_click`: …
=> Support for E1810 as media player controller

apps/controllerx/core/type/light_controller.py, apps/controllerx/devices/ikea.py, tests/core/type/light_controller_test.py
This adds zha support for the ICTC-G-1 controller.
The device is VERY chatty with zha_event so the sometimes the behaviour is a little wonky. The dimmer I tested with isn't the latest firmware so I will try and update it and see if that makes any difference.
Note that I used Light.HOLD_BRIGHTNESS_DOWN and Light.HOLD_BRIGHTNESS_UP twice as there are two different args, depending on the rate at which you rotate the dimmer - slow or fast. This is still separate from "quick" right and left. I tried with no args (just "move" and "move_with_on_off" but then I got no dimming at all with rotation - maybe an issue with args processing?
=> zha support for ICTCG1Controller

apps/controllerx/controllerx.py, apps/controllerx/core/integration/zha.py, apps/controllerx/devices/samjin.py
This adds support for z2m, zha and deconz for the Samjin Button.
[https://www.samsung.com/ca/smart-things/button/](url)
Had to work around zha processing of the args which needs to be fixed prior to implementation - filed and issue (#33) to explore other options.
=> Support SmartThings/Samjin Button

apps/controllerx/controllerx.py, apps/controllerx/devices/lutron.py
This adds both media player and light controller support for lutron pico remotes for those of us using the lutron-caseta-pro integration by upsert - https://github.com/upsert/lutron-caseta-pro
Also adds zha and deconz support for the connected bulb remote (LZL-4B-WH-L01) while I was at it :-)
Addresses #38
=> Lutron support

docs/examples/sonos.md
There were two entries of brightness_up_release. One of them should be brightness_down_release
=> Fix for wrong sonos example

apps/controllerx/devices/philips.py, docs/_data/controllers/hue-dimmer-switch.yml
This adds (limited) support for using the HueDimmerController with ZHA.
At least for my dimmer, no hold-events for the on and off buttons were created, so I could not add those.
=> Add ZHA support for HueDimmerController

apps/controllerx/cx_devices/ikea.py
Zigbee2mqtt changed E1744 messages changed
from:
rotate_left, rotate_right, rotate_stop, play_pause, skip_forward, skip_backward
to:
brightness_move_down, brightness_move_up, brightness_stop, toggle, brightness_step_up, brightness_step_down
=> Ikea E1744 fixed for z2m version 1.14.1

apps/controllerx/controllerx.py, apps/controllerx/cx_core/controller.py, apps/controllerx/cx_core/integration/zha.py, apps/controllerx/cx_devices/aqara.py, apps/controllerx/cx_devices/legrand.py, docs/_data/controllers/LEGRAND-600083.yml, docs/_data/controllers/LEGRAND-600088.yml, docs/controllers/LEGRAND-600083.md, docs/controllers/LEGRAND-600088.md, tests/cx_devices/aqara_test.py, tests/cx_devices/legrand_test.py
This adds support for the Legrand [simple wall switch - 6 000 83](https://www.legrand.fr/pro/catalogue/42796-version-dooxie-with-netatmo/commande-sans-fil-dooxie-with-netatmo-pour-eclairage-ou-prise-connectee-ou-micromodule-blanc).
I originally posted this snippet in #98.
=> Add support for legrand simple wall switch

docs/examples/tasmota-switchmode11.md
Update of Tasmota swithcmode 11/12 / ControllerX examples.
- Tasmota rules changed from MQTT payload state 'form'  to events with key and command as JSON objects
- Added use of new DOUBLE press action switchstate to examples
- Small changes in description text here and there...
Ciao ! 😎
=> Update tasmota-switchmode example

apps/controllerx/cx_core/integration/z2m.py, tests/cx_core/integration/z2m_test.py
I've ran into the following error when using the Tradfri E1744 controller: 
```
Sep 16 17:11:26 flip appdaemon[26288]: 2020-09-16 17:11:26.828990 WARNING sound_controller_sideroom: ------------------------------------------------------------
Sep 16 17:11:26 flip appdaemon[26288]: 2020-09-16 17:11:26.829247 WARNING sound_controller_sideroom: Traceback (most recent call last):
Sep 16 17:11:26 flip appdaemon[26288]:   File "/home/homeassistant/appdaemon/lib/python3.7/site-packages/appdaemon/threading.py", line 838, in async_worker
Sep 16 17:11:26 flip appdaemon[26288]:     await funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
Sep 16 17:11:26 flip appdaemon[26288]:   File "/home/homeassistant/homeassistant/appdaemon/apps/controllerx/cx_core/integration/z …
```
=> Fix KeyError in z2m integration

apps/controllerx/cx_devices/aqara.py
Updated payloads for 'action' command as 'click' has been deprecated.
Examples documentation also need revision for these and the controller class as well as 'DoubleKeyWirelessAqaraController' has been revised to 'WXKG02LMLightController'
=> WXKG02LM 'action' payload revision as 'click' will be deprecated

apps/controllerx/cx_core/integration/z2m.py
Different actions can now be performed by different light groups. e.g. You can control both lights and music player.
Works only with `listen_to: mqtt` because we need more data than HASS integration provides (`listen_state` returns just target `on`/`off` state, while `listen_event` returns the entire `zigbee2mqtt`'s payload).
Example payload: `{"linkquality":36,"action":"off","action_group":146}`
Light groups are mapped as follows:
- light 1 - `145`
- light 2 - `146`
- light 3 - `147`
- light 4 - `148`
- light 5 - `149`
- all lights - `150`
Example from my `apps.yaml` configuration:
```
trust_remote_1:
module: controllerx
class: ZYCT202LightController
controller: "Z2M NAME"
integration:
name: z2m
listen_to: mqtt
action_group:
- 145
- 150
light: light.LIGHT_NAME_1
trust_remote_2:
module: …
```
=> Add support for different group actions on ZYCT-202 on z2m(mqtt)

apps/controllerx/cx_devices/ikea.py, docs/_data/controllers/E1766.yml
Holding the up and down fires the same event as a click up/down with a stop event on the release.
=> Add ZHA support for Ikea E1766 remote

apps/controllerx/cx_devices/legrand.py, docs/_data/controllers/LEGRAND-600083.yml, docs/_data/controllers/LEGRAND-600088.yml
⚠️ I've not tested it locally but I'm confident since these are the states published on MQTT and found in the `*_action` sensor 😇
=> Support Z2M for Legrand controllers

apps/controllerx/cx_core/type/media_player_controller.py
=> check if source_list is None before treating as array

docs/docs/start/integrations.md
Changed instances of: "Only applicable is `listen_to` [...]"  to "Only applicable if `listen_to` [...]"
=> Fix a few typos in integrations.md

RELEASE_NOTES.md, apps/controllerx/cx_devices/philips.py
This PR fixes problem mention in this comment: https://github.com/xaviml/controllerx/issues/616#issuecomment-1306747710 from @Dennis-Q.
=> fix(device): fix Z2M mapping for Philips929003017102

RELEASE_NOTES.md, apps/controllerx/cx_const.py, apps/controllerx/cx_core/controller.py, apps/controllerx/cx_devices/adeo.py, apps/controllerx/cx_devices/aqara.py, apps/controllerx/cx_devices/homematic.py, apps/controllerx/cx_devices/muller_licht.py, apps/controllerx/cx_devices/osram.py, apps/controllerx/cx_devices/philips.py, apps/controllerx/cx_devices/rgb_genie.py, apps/controllerx/cx_devices/tasmota.py, docs/main.py, tests/integ_tests/merge_mapping/config.yaml, tests/integ_tests/merge_mapping/fake_step_test.yaml, tests/integ_tests/muller_licht_z2m/none_action_test.yaml, tests/unit_tests/cx_devices/devices_test.py
- Fix: Allow running configuration with null actions.
- Docs: Device pages - show events with no actions assigned.
=> fix(core): allow null mapping

RELEASE_NOTES.md, apps/controllerx/cx_core/controller.py, apps/controllerx/cx_core/fix_template.py, pyproject.toml
This PR fixes an AppDaemon 4.4.0 and 4.4.1 bug:
https://github.com/AppDaemon/appdaemon/issues/1747
It seems that the problem has been fixed (https://github.com/AppDaemon/appdaemon/pull/1750),
but it is not known when the fix will be released.
This entire file can be deleted once the fix is in place officially from AppDaemon.
=> fix: temporary fix to template rendering

RELEASE_NOTES.md, apps/controllerx/cx_core/controller.py, apps/controllerx/cx_core/fix_template.py
=> fix: issue with template rendering in AppDaemon addon

RELEASE_NOTES.md, apps/controllerx/cx_devices/sengled.py
Adds in ZHA support for the Sengled E1E G7F ZigBee remote controller using same default actions as Z2M.
Tested locally and works as expected.
Looks like your docs are now completely dynamic (cool!) so let me know if you need any other PRs for this.
Thanks!
=> Support ZHA for Sengled E1EG7FLightController

apps/controllerx/cx_devices/philips.py
Hi!
I noticed that the Hue Wall Switch Module only had deconz and z2m support, so this is a stab at adding ZHA support.
I am very much a beginner when it comes to HA and ControllerX, I am not even sure how to test this 🙈 .
I did examine the `zha_event`s that were sent when clicking on my Wall Switch Module, and the event names matched up perfectly with the event names that were already defined in `get_z2m_actions_mapping`. Therefore I think it could be correct to copy-paste that one.
I'm happy for any guidance to take this over the finish line :)
=> add RDM001 (Philips) ZHA support

apps/controllerx/cx_core/type/z2m_light_controller.py
Same as the normal light_controller.
Works fine with Zigbee2Mqtt.
=> z2m_light_controller - allow attributes for toggle-action

RELEASE_NOTES.md, apps/controllerx/cx_devices/tuya.py
I forgot a commit on my last PR  #1076 (sorry)
As I said before, I use Open and Close action rather than toggle actions as there is already a stop button on the controller.
There's also a weird behavior with toggle actions where toggle_open stop a closing action rather than opening the cover.
I suppose this is correct for a two buttons controller, but not for a three buttons one.
---
Also there is a small mistake in the release notes of [v4.28.0](https://github.com/xaviml/controllerx/releases/tag/v4.28.0): 
🎮 New devices
[TS0042](https://xaviml.github.io/controllerx/controllers/TS0042) - add device with ZHA support. [ https://github.com/xaviml/controllerx/pull/1065 ] @Strauman
[TS0043](https://xaviml.github.io/controllerx/controllers/TS0043) - add ZHA support. [ …
=> Fix TS0043 Cover Controller

RELEASE_NOTES.md, apps/controllerx/cx_devices/ikea.py
The Ikea E2123 Medie Player controller has a toggle button to play/pause. However, the mapping was set to "PLAY" instead of "PLAY_PAUSE", so it was not possible to pause the media player.
Pausing was only possible with a custom
merge_mapping: 
toggle: play_pause
(Note: the same button is named "toggle" or "play_pause" depending on the firmware of the device)
=> E2123 Media Player Controller: toggle play/pause

RELEASE_NOTES.md, apps/controllerx/cx_devices/ikea.py
I added ZHA support for the Ikea E2123 media remote. Tested with my own remote and homeassistant instance, seems to be working great! It's been a long time since I've written any python, so let me know if there's a better way to go about this (particularly the get_zha_action method).
=> Added ZHA support for the Ikea E2123 media remote
